### ISSUE TITLE
Runner not recognizing movement

### ISSUE THREAD

**Issue by iilis** [sandermvanvliet/RoadCaptain#111]
I mentioned this on my post about the Volcano Climb back in Oct. but still having this issue.  (https://github.com/sandermvanvliet/RoadCaptain/issues/101#issuecomment-1278214226)

The Runner isn't recognizing that I am moving on the bike.  It keeps saying “Start Pedaling,” even after I had gone 0.2 mi and passed the Start Banner (downtown Watopia).  (So, didn’t get to test routing on the Volcano climb.)

**Application Details**
Zwift version : 1.31.1
Zwift device : Desktop PC (Windows 10)
Road Captain version : 0.6.9.0

I’m wondering if it could be that I’m just not starting the app along with Zwift in the proper order or something else I’m doing wrong?

Here is the order in which I open the two apps:
1. Zwift: Open, Log in, then get to to Menu screen
2. RC Runner: Open, Log in, Select Route, wait until it says which Zwift route to select
3. Zwift: Select World and route, then click “Start”
4. RC Runner: Bring window to front (on top of Zwift) 

**Additional Info**
(Tried same route back on Nov. 8 and again on Dec. 1.)

[TitanVsDragon.json.txt](https://github.com/sandermvanvliet/RoadCaptain/files/10141147/TitanVsDragon.json.txt)
[roadcaptain-runner-log-2022-11-08T211019.log](https://github.com/sandermvanvliet/RoadCaptain/files/10141149/roadcaptain-runner-log-2022-11-08T211019.log)
[roadcaptain-runner-log-2022-12-01T205853.log](https://github.com/sandermvanvliet/RoadCaptain/files/10141150/roadcaptain-runner-log-2022-12-01T205853.log)
[Log_2022-11-08.txt](https://github.com/sandermvanvliet/RoadCaptain/files/10141154/Log_2022-11-08.txt)
[Log_2022-12-01.txt](https://github.com/sandermvanvliet/RoadCaptain/files/10141158/Log_2022-12-01.txt)

**Comment by sandermvanvliet** [comment]
Hey @iilis 
sorry to not have made a lot of progress on this, I’ve just started a new job so you can imagine that it sucks up a lot of time at the moment.

I hope to take a look at soon 👍

**Comment by sandermvanvliet** [comment]
@iilis I think I've found what the problem is...

A while ago I introduced a position log to help troubleshooting connectivity issues, this worked by creating a file and dumping position updates to it.

However the file was created in the application installation directory, and the application doesn't have permissions to write files there (because `Program Files` is read-only to the app) so that failed. Because this initialization happens in the `EnterGame` phase it would prevent RoadCaptain from actually entering the game and it was just stuck.

I've fixed this so that the position log file is now created in the user data directory where the log files also get written and this problem should now be fixed (as of 270dbbbb89304622b45e65cb2944926601d83c76) 

I'm triggering a preview release build now and will update here when that's available for testing 👍

**Comment by sandermvanvliet** [comment]
Installer will appear here shortly: [Pre-release 0.6.10.1](https://github.com/sandermvanvliet/RoadCaptain/releases/tag/prerelease%2F0.6.10.1)

**Comment by iilis** [comment]
Thanks for the help.

Is there anything wrong with the order in which I’m loading up the 2 apps (in my original post)?  Just want to make sure I wasn’t doing something wrong, as well...

**Comment by sandermvanvliet** [comment]
No that’s fine, pretty much how I do that. 
The order isn’t really important but I know that sometimes Zwift takes a while so sync up with their back-end and it doesn’t respond to the pairing request very quickly

**Comment by iilis** [comment]
Looks like this update fixes this issue.  Created a new test route and tried it today.  Everything seems to be running well.
Didn’t try the Volcano Climb as I just wasn’t up for after my ride yesterday!  So will try that some time soon (hopefully)!
Thanks!

Here is the route, if you’re curious:
[TestRoute.json.txt](https://github.com/sandermvanvliet/RoadCaptain/files/10369149/TestRoute.json.txt)

**Comment by sandermvanvliet** [comment]
That’s great 👍

I’m going to make an official release for this now. Thanks for testing!
