### ISSUE TITLE
Cannot turn right before the JWB onto the Bridge/Islands Bypass

### ISSUE THREAD

**Issue by sigurdhes** [sandermvanvliet/RoadCaptain#37]
![image](https://user-images.githubusercontent.com/104097267/164770994-3f3d1b87-95ca-4cdb-9a0a-d8ea57518e68.png)

I cannot select the "Italian Villas loop 3" segment after "Italian Villas loop 4" segment (same order as in the "Beach Island loop"). Is this due to the fact that the red dot is to big, obstructing the segment? (could the dots not increase in size when zooming?)

Sigurd

**Comment by sandermvanvliet** [comment]
From my testing it seems that there isn’t actually a turn from this direction to take that right turn there 😑

It may be possible that it works in events but that’s not possible in a “normal” free ride unfortunately. 

When Zwift doesn’t present the turn buttons then RoadCaptain can’t make a turn either.

Let me know if you’re able to make that turn normally in the game because in that case I’ll add it to the segment turns!

**Comment by sigurdhes** [comment]
The turn is used in the route "beach Island loop", but I don't remember whether I've done it manually.

**Comment by sandermvanvliet** [comment]
Adding this here for reference: https://zwiftinsider.com/route/beach-island-loop/

I’ll need to check this out in-game to see if the turn controls come up
