### ISSUE TITLE
Add / Display Region name, .. and Sprint/Kom/ Point of interest 

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#46]
I dream to have the legit Zwift background map -- as [ZwiftMap for Strava addon](https://chrome.google.com/webstore/detail/zwiftmap-for-strava/eiaekjobfimlijhpggbbkhoihlchdhdl) -- is doing forStrava, anyway I recall right that Zwift world have region name, such as [Watopia Course Map](https://zwiftinsider.com/wp-content/uploads/2020/12/Watopia-2.14.pdf) (not updated here) have.

Also why not display those Sprint/Kom/ POI name as well ?

Thanks.

**Comment by sandermvanvliet** [comment]
I’m not showing the Zwift maps because I don’t know if that’s legal. 
Even though the Zwift map for Strava extension exists and doesn’t seem to get taken down it _probably_ is fine but I’m being cautious here. 

The names of segments I’m not showing (only on hover) because it clutters up the map quite a bit.

**Comment by VNT974** [comment]
Only on hover are really nice, I do agree. Wast thinking of that as well.

**Comment by sandermvanvliet** [comment]
Hover for KOM and sprint already works but might not be super obvious. 
really need to add a help/manual something to the apps

**Comment by sandermvanvliet** [comment]
World map view has been implemented (See #90) and will be released in 0.6.4.0
From discussions on Twitter (see other issue) it turns out that Zwift has no problems with this.
