### ISSUE TITLE
Currently Reset Route =  Back to Welcome Screen ?  Misinterpretation ?

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#47]
As a non-native english speaker, I do understand that Reset Route = reset / delete current segments in current session. The feature do probably work as expected, but I found it a little confusing. I still have this Reset Route in the Welcome Screen (where I have to select Sport / Discipline).

As we have already a dialogue box telling us that the selected sport will be set as default, what we currently have is only a World selection.

Wouldn't better to:

Reset route means  reset/clear/delete ALL selected segments in current session
Reset route button should not be available when we select World, in the  Welcome Screen
A new World selection button which reset/clear/delete ALL selected segments

**Comment by sandermvanvliet** [comment]
This is indeed an annoying action. It's basically because the reset button did in fact mean "remove all segments from the route" as only Watopia was supported so world selection wasn't a thing back then.

I've been thinking of improving the buttons to reflect this, I'll probably go with:

- A button with a globe icon that returns to the world selection view. If you have segments selected it will ask you to save/discard
- The current reset button which will clear the route

**Comment by VNT974** [comment]
Agree with those ideas.
Same about the welcome page, probably Zoom In/Out, Simulate route button shouldn't be here as well.

**Comment by sandermvanvliet** [comment]
The zoom buttons are now hidden there, fixed that in #39 which is included in the 0.6.2.0 release.
