### ISSUE TITLE
While uninstalling, there are still 2 folders in User/AppData/Local

### ISSUE THREAD

**Issue by VNT974** [sandermvanvliet/RoadCaptain#74]
When I uninstall, I kinda like that all folders are completly removed, unless there are options saying to keep profile data, here, in User/AppData/Local I do have 2 folders remaining:

Codenizer BV contains log files, 
Codenizer_BV  contains user.config, several folder based on version

**Comment by sandermvanvliet** [comment]
As far as I know this is by design and a Windows standard thing (at least I’ve seen other apps behave the same)

**Comment by sandermvanvliet** [comment]
It’s also fairly dangerous for an installer to remove user specific data as it can’t tell if anything that’s in those folders is actually safe to delete. 
Also, the installer doesn’t know about these folders as they don’t contain files included in the installer. They are created at runtime only. 
Because of that it doesn’t know to remove them.

**Comment by VNT974** [comment]
I understand, I expected to have at least 1 folder in User/AppData/Local instead of 2, it's better to clean up things in the disk.

**Comment by sandermvanvliet** [comment]
This will be solved in the upcoming release (the cross-platform release). 
I’ve reworked the settings storage which takes care of the second set of folders as they will no longer be created.
